name: mcp-confluent
lang: node
lang_version: "22"
git:
  enable: true
codeowners:
  enable: true
renovatebot:
  enable: false
  automerge:
    enable: true
sonarqube:
  enable: true
  languages:
    - javascript
    - typescript
  coverage_sources:
    - "src"
  coverage_exclusions:
    - "src/**/*.test.ts"
    - "src/**/*.d.ts"
  coverage_reports:
    - "coverage/lcov.info"
  main_branch: main
semaphore:
  enable: true
  pipeline_enable: false
  status_level: block
  tasks:
    - name: create-github-tag
      branch: main
      pipeline_file: .semaphore/create-github-tag.yml
      parameters:
        - name: TAG_NAME
          required: true
          description: The name of the tag to be created.
          default_value: "X.Y.Z"
