### service-bot sonarqube plugin managed file
sonar.coverage.exclusions=**/test/**/*,**/tests/**/*,**/mock/**/*,**/mocks/**/*,**/*mock*,**/*test*
sonar.cpd.exclusions=**/test/**/*,**/tests/**/*,**/mock/**/*,**/mocks/**/*,**/*mock*,**/*test*
sonar.exclusions=**/*.pb.*,**/mk-include/**/*,src/**/*.d.ts,src/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.language=javascript,typescript
sonar.projectKey=mcp-confluent
sonar.sources=src
sonar.typescript.coverage.reportPaths=coverage/lcov.info
