export enum ToolName {
  LIST_TOPICS = "list-topics",
  CREATE_TOPICS = "create-topics",
  DELETE_TOPICS = "delete-topics",
  PRODUCE_MESSAGE = "produce-message",
  LIST_FLINK_STATEMENTS = "list-flink-statements",
  CREATE_FLINK_STATEMENT = "create-flink-statement",
  READ_FLINK_STATEMENT = "read-flink-statement",
  DELETE_FLINK_STATEMENTS = "delete-flink-statements",
  LIST_CONNECTORS = "list-connectors",
  READ_CONNECTOR = "read-connector",
  CREATE_CONNECTOR = "create-connector",
  DELETE_CONNECTOR = "delete-connector",
  SEARCH_TOPICS_BY_TAG = "search-topics-by-tag",
  SEARCH_TOPICS_BY_NAME = "search-topics-by-name",
  CREATE_TOPIC_TAGS = "create-topic-tags",
  DELETE_TAG = "delete-tag",
  REMOVE_TAG_FROM_ENTITY = "remove-tag-from-entity",
  ADD_TAGS_TO_TOPIC = "add-tags-to-topic",
  LIST_TAGS = "list-tags",
  ALTER_TOPIC_CONFIG = "alter-topic-config",
  LIST_CLUSTERS = "list-clusters",
  LIST_ENVIRONMENTS = "list-environments",
  READ_ENVIRONMENT = "read-environment",
}
